@startuml DocumentModel

hide empty members

class "MedComNotesBundle" as document <<MedComDocumentBundle>>
class "MedComNotesComposition" as composition <<MedComDocumentComposition>>

class "MedComDocumentOrganization" as organization <<MedComCoreOrganization>>
class "MedComDocumentPractitioner" as practitioner <<MedComCorePractitioner>>
class "MedComDocumentPractitionerRole" as practitionerrole <<MedComCorePractitionerRole>>
class "MedComDocumentPatient" as patient <<DkCorePatient>>
class "MedComNotesObservation" as content <<MedComDocumentObservation>>

' Fælles abstraktion for alle, der kan være author:person
interface "AuthorPerson" as authorPerson

' --- Struktur på dokumentet ---
document -- composition : "entry"

' Composition peger på den fælles type
composition -- authorPerson : "author person"
composition -- organization : "author organization"
composition -- patient : "subject"
composition -- content : "section.entry"

' PractitionerRole’s egne relationer bevares
practitionerrole -- practitioner : "practitioner"
practitionerrole -- organization : "organization"

' Hvilke typer kan være author:person?
authorPerson <|.. practitioner
authorPerson <|.. practitionerrole

content -- patient : "subject"
content -- organization : "performer organization"
content -- authorPerson : "perfomer person"

@enduml
